# 2D NUMPY ARRAYS

In [1]:
# 2D Array Creation
# Similar to 1D array creation np.array()
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
# Cast a list into a numpy array
a  = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [3]:
# To check number of dimensions
print(A.ndim)

# To check the shape of the array --- (no. of nested lists in the og list, size of each of the nested list)
print(A.shape)

# To check the size of the array as a whole
print(A.size)

2
(3, 3)
9


In [5]:
# Indexing and Slicing
# Accessing the elements of 2D array
print(A[0][0], A[0][1], A[0][2]) # access row 1 elements by first index
print(A[1][0], A[1][1], A[1][2]) # access row 2 elements
print(A[2][0], A[2][1], A[2][2]) # acess row 3 elements 

11 12 13
21 22 23
31 32 33


In [6]:
# Access the element on the second row and third column
A[1][2]

23

In [8]:
# SLICING : Access the element on the first row and first and second columns
print(A[0, 0:2])

# Access the element on the first and second rows and third column
print(A[0:2, 2])

[11 12]
[13 23]


In [10]:
# BASIC OPERATIONS
# Adding arrays
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])
Z = X + Y 
Z

array([[3, 1],
       [1, 3]])

In [11]:
# Multiplying with a scalar
Z = 2 * Y 
Z

array([[4, 2],
       [2, 4]])

In [12]:
# HARDAMARD PRODUCT --- Multiplying two arrays
Z = X * Y 
Z

array([[2, 0],
       [0, 2]])

In [14]:
# MATRIX MULTIPLICATION ---- use the dot product
K = np.array([[0, 1, 1], [1, 0, 1]])
L = np.array([[1,1], [1, 1], [-1, 1]])
M = np.dot(K, L)
M

array([[0, 2],
       [0, 2]])

In [15]:
np.sin(M)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [16]:
# Get the Transposed of M
# The transpose of a matrix is found by interchanging its rows into columns or columns into rows. 
# The transpose of the matrix is denoted by using the letter “T”
M.T

array([[0, 0],
       [2, 2]])